[project]
name = "waypoint"
version = "0.1.0"
description = "Finding the shortest flight combination between two airports."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]
